version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_data_base
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  postgres2:
    image: postgres:16
    container_name: postgres_data_base_test
    environment:
      POSTGRES_USER: ${DB_USER_TEST}
      POSTGRES_PASSWORD: ${DB_PASS_TEST}
      POSTGRES_DB: ${DB_NAME_TEST}
    ports:
      - "5433:5432"
    volumes:
      - pg_data_2:/var/lib/postgresql/data

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pedant_bot
    depends_on:
      - postgres
      - postgres2
    env_file:
      - .env
    volumes:
      - .:/pedant_killer

volumes:
  pgdata:
  pg_data_2: