services:
  postgres:
    image: postgres:16
    container_name: postgres_data_base
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pedant_killer007
      POSTGRES_DB: pedant_killer_data_base
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata1

  postgres2:
    image: postgres:16
    container_name: postgres_data_base_test
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin2
      POSTGRES_PASSWORD: pedant_killer007
      POSTGRES_DB: postgres
    volumes:
      - pg_data_2:/var/lib/postgresql/data2

volumes:
  pgdata:
  pg_data_2: