"""fix_bug55

Revision ID: 0de93e8dfde1
Revises: f6bc9c4dfb40
Create Date: 2024-12-13 16:31:31.811127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0de93e8dfde1'
down_revision: Union[str, None] = 'f6bc9c4dfb40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
