"""fix_bug51

Revision ID: 0dfb5e0c3b6c
Revises: cfa442a2cbc4
Create Date: 2024-12-10 18:05:45.538379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dfb5e0c3b6c'
down_revision: Union[str, None] = 'cfa442a2cbc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
