"""fix_bug69

Revision ID: 16302d12e86d
Revises: ad9c3748cd93
Create Date: 2024-12-13 19:57:07.625138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16302d12e86d'
down_revision: Union[str, None] = 'ad9c3748cd93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('indx_uniq', 'order_device_service', ['order_id', 'device_service_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('indx_uniq', 'order_device_service', type_='unique')
    # ### end Alembic commands ###
