"""third migration

Revision ID: 30b37541ef57
Revises: c55e12e99143
Create Date: 2024-11-10 00:59:49.597390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30b37541ef57'
down_revision: Union[str, None] = 'c55e12e99143'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('name_model', sa.String(), nullable=False))
    op.drop_column('device', 'model_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('model_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('device', 'name_model')
    # ### end Alembic commands ###
