"""fix_bug49

Revision ID: 5168bb5a08e0
Revises: fc3004376375
Create Date: 2024-12-10 17:32:19.370376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5168bb5a08e0'
down_revision: Union[str, None] = 'fc3004376375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_device_service',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('device_service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_service_id'], ['device_service.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('order_id', 'device_service_id')
    )
    op.drop_table('order_device_service_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_device_service_table',
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('device_service_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_service_id'], ['device_service.id'], name='order_device_service_table_device_service_id_fkey'),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name='order_device_service_table_order_id_fkey'),
    sa.PrimaryKeyConstraint('order_id', 'device_service_id', name='order_device_service_table_pkey')
    )
    op.drop_table('order_device_service')
    # ### end Alembic commands ###
