"""fix_bug2

Revision ID: 674e4a4821c1
Revises: d2121a23f54e
Create Date: 2024-11-14 16:00:32.312576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '674e4a4821c1'
down_revision: Union[str, None] = 'd2121a23f54e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('device_service', 'work_duration',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('device_service', 'work_duration',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
