"""fix_bug75

Revision ID: 6d748ece43a9
Revises: 1acf79f8a404
Create Date: 2024-12-13 20:11:19.587000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d748ece43a9'
down_revision: Union[str, None] = '1acf79f8a404'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_device_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('device_service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_service_id'], ['device_service.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'device_service_id', name='indx_uniq')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_device_service')
    # ### end Alembic commands ###
