"""fix_bug8

Revision ID: 8d3f260acdf3
Revises: e171e324f37a
Create Date: 2024-11-22 00:46:38.807059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d3f260acdf3'
down_revision: Union[str, None] = 'e171e324f37a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'master_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order', 'sent_from_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('order', 'return_to_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('order', 'comment',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('order', 'rating',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'rating',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('order', 'comment',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('order', 'return_to_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('order', 'sent_from_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('order', 'master_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
