"""fix_bug68

Revision ID: ad9c3748cd93
Revises: 409fa8d064d5
Create Date: 2024-12-13 19:55:05.469579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad9c3748cd93'
down_revision: Union[str, None] = '409fa8d064d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('indx_uniq', 'order_device_service', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('indx_uniq', 'order_device_service', ['order_id', 'device_service_id'])
    # ### end Alembic commands ###
