"""fix_bug70

Revision ID: b1cf835d54c8
Revises: 16302d12e86d
Create Date: 2024-12-13 20:01:22.348730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1cf835d54c8'
down_revision: Union[str, None] = '16302d12e86d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('indx_uniq', 'order_device_service', type_='unique')
    op.create_unique_constraint('indx_uniq', 'order_device_service', ['id', 'order_id', 'device_service_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('indx_uniq', 'order_device_service', type_='unique')
    op.create_unique_constraint('indx_uniq', 'order_device_service', ['order_id', 'device_service_id'])
    # ### end Alembic commands ###
