"""second_migration

Revision ID: c55e12e99143
Revises: e9f73c5b6271
Create Date: 2024-11-10 00:35:20.586898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c55e12e99143'
down_revision: Union[str, None] = 'e9f73c5b6271'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('model_name', sa.String(), nullable=False))
    op.drop_column('device', 'model')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('device', 'model_name')
    # ### end Alembic commands ###
