"""fix_bug32

Revision ID: cc2ae1de73f6
Revises: a0bdf76e9afa
Create Date: 2024-12-01 14:48:28.020534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc2ae1de73f6'
down_revision: Union[str, None] = 'a0bdf76e9afa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
