"""fourth

Revision ID: d2121a23f54e
Revises: 30b37541ef57
Create Date: 2024-11-12 01:18:48.552697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2121a23f54e'
down_revision: Union[str, None] = '30b37541ef57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('device_type', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('manufacturer', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('manufacturer', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('device_type', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
