"""fix_bug35

Revision ID: dd2eb8a420b0
Revises: cc2ae1de73f6
Create Date: 2024-12-10 12:47:37.279302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd2eb8a420b0'
down_revision: Union[str, None] = 'cc2ae1de73f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_device_service',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('device_service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_service_id'], ['device_service.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('order_id', 'device_service_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_device_service')
    # ### end Alembic commands ###
