"""fix_bug52

Revision ID: f4ae07294aa5
Revises: 0dfb5e0c3b6c
Create Date: 2024-12-10 18:20:29.036287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4ae07294aa5'
down_revision: Union[str, None] = '0dfb5e0c3b6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
