"""fix_bug59

Revision ID: fb70dc2c267e
Revises: 439e00cdcd41
Create Date: 2024-12-13 17:52:30.098890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb70dc2c267e'
down_revision: Union[str, None] = '439e00cdcd41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_device_service', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('order_device_service', 'device_service_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_device_service', 'device_service_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order_device_service', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
