"""fix_bug48

Revision ID: fc3004376375
Revises: 6ee0c798f5ac
Create Date: 2024-12-10 17:31:15.500642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc3004376375'
down_revision: Union[str, None] = '6ee0c798f5ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_device_service_table',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('device_service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_service_id'], ['device_service.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('order_id', 'device_service_id')
    )
    op.drop_table('order_device_service')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_device_service',
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('device_service_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_service_id'], ['device_service.id'], name='order_device_service_device_service_id_fkey'),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name='order_device_service_order_id_fkey'),
    sa.PrimaryKeyConstraint('order_id', 'device_service_id', name='order_device_service_pkey')
    )
    op.drop_table('order_device_service_table')
    # ### end Alembic commands ###
