name: Lint and format python code with ruff
run-name: Pedant killer check ${{ github.run_number }} by @${{ github.actor }}
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with=dev

      - name: Run Ruff linter
        run: poetry run python -m ruff check --output-format=github --exit-zero .

      - name: Run Ruff formatter
        run: poetry run python -m ruff format --diff . > ruff_diff.txt

      - name: Upload Ruff diff as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: ruff-diff
          path: ruff_diff.txt

      - name: Comment on pull request
        if: failure()
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            **Ruff Formatting Issues:**
            ```diff
            $(cat ruff_diff.txt)
            ```
