name: Lint and format python code with ruff
run-name: Pedant killer check ${{ github.run_number }} by @${{ github.actor }}
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with=dev

      - name: Run Ruff linter
        run: poetry run python -m ruff check --output-format=github --exit-zero .

      - name: Register problem matcher
        run: echo "::add-matcher::.github/workflows/matchers/ruff.json"

      - name: Run Ruff formatter
        run: poetry run python -m ruff format --check .
